package ch.klara.luz.store.model;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerPricingModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String legalForm;
	private java.lang.String nogaCode;
	private java.lang.String region;

	private Date customerSinceDate;

	private java.lang.String name;

	private java.lang.String corporateIdentificationNumber;

	private java.lang.String internetAddress;

	private java.lang.String socialNetwork;

	private java.lang.String industryCode;

	private java.lang.String customerType;

	public CustomerPricingModel() {
	}

	public java.lang.String getLegalForm() {
		return this.legalForm;
	}

	public void setLegalForm(java.lang.String legalForm) {
		this.legalForm = legalForm;
	}

	public java.lang.String getNogaCode() {
		return this.nogaCode;
	}

	public void setNogaCode(java.lang.String nogaCode) {
		this.nogaCode = nogaCode;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.util.Date getCustomerSinceDate() {
		return this.customerSinceDate;
	}

	public void setCustomerSinceDate(java.util.Date customerSinceDate) {
		this.customerSinceDate = customerSinceDate;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getCorporateIdentificationNumber() {
		return this.corporateIdentificationNumber;
	}

	public void setCorporateIdentificationNumber(
			java.lang.String corporateIdentificationNumber) {
		this.corporateIdentificationNumber = corporateIdentificationNumber;
	}

	public java.lang.String getInternetAddress() {
		return this.internetAddress;
	}

	public void setInternetAddress(java.lang.String internetAddress) {
		this.internetAddress = internetAddress;
	}

	public java.lang.String getSocialNetwork() {
		return this.socialNetwork;
	}

	public void setSocialNetwork(java.lang.String socialNetwork) {
		this.socialNetwork = socialNetwork;
	}

	public java.lang.String getIndustryCode() {
		return this.industryCode;
	}

	public void setIndustryCode(java.lang.String industryCode) {
		this.industryCode = industryCode;
	}

	public java.lang.String getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(java.lang.String customerType) {
		this.customerType = customerType;
	}

	public CustomerPricingModel(java.lang.String legalForm,
			java.lang.String nogaCode, java.lang.String region,
			java.util.Date customerSinceDate, java.lang.String name,
			java.lang.String corporateIdentificationNumber,
			java.lang.String internetAddress, java.lang.String socialNetwork,
			java.lang.String industryCode, java.lang.String customerType) {
		this.legalForm = legalForm;
		this.nogaCode = nogaCode;
		this.region = region;
		this.customerSinceDate = customerSinceDate;
		this.name = name;
		this.corporateIdentificationNumber = corporateIdentificationNumber;
		this.internetAddress = internetAddress;
		this.socialNetwork = socialNetwork;
		this.industryCode = industryCode;
		this.customerType = customerType;
	}

}